// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "lang": "ara",
  "title": "مرحبا!",
  "Message": "هذه هي اللغة العربي",
  "goefttapping": "انطلق بالنقرEFT ",
  "thesound": "",
  "yourrecording": "",
  "copyright": "",
  "eftintro": "مقدمة عن الحرية الانفعالية",
  "youreft": "الحرية الانفعالية الخاصة بك",
  "contactme": "اكتب لي",
  "sharingiscaring": "المشاركة تعنى الاهتمام!",
  "disclaimer": "من خلال الاستخدام المستمر لهذا التطبيق ، فإنك تتحمل مسؤولية صحتك.",
  "myfeeling": "شعوري أوأعراضي\n هي ....",
  "theintensity": "شدّة الأعراض\n (10<-0)...",
  "myfeelingrecorded": "تم تسجيل  شعوري\n أوأعراضي",
  "theintensityrecorded": "تم تسجيل الشّدة",
  "recordproblem": "سجل مشكلتك",
  "recordintensity": "سجل درجة\n قوة المشكلة",
  "recordingproblem": "تسجيل...",
  "recordingintensity": "تسجيل...",
  "chooselanguage": "اختر اللغة",
  "recordprefferedemotion": "قم بالتسجيل",
  "recording": "تسجيل...",
  "record": "قم بالتسجيل",
  "whenihavethis": "عندما يكون لدي هذا\n (الشعور/الأعراض)",
  "ichoosetofeel": " فإني اختار الاحساس \n:(الشعور المفضل لدي)",
  "ihaveaquestion": "I have a question",
  "hellosara": "Hello",
  "acupoints2": "2. أعلى الرأس\n3. حاجب العين\n4. جانب العين\n5. تحت العين\n6. تحت الأنف\n7. الذقن\n8. الترقوة\n'عقدة ربطة العنق'\n9. تحت الإبط\n10.  داخل الكم\n(معصم اليد)",
  "acupoints": "1. منطقة ضربة \n الكاراتيه",
  "pagebtitle": "سجل مشكلتك",
  "pageetitle": "نضغط معا",
  "pageftitle": "جسر للتحسين",
  "checkout": "check out GO EFT TAPPING app!",
  "takealook": "Take a look at this app!"
};
static const Map<String,dynamic> en = {
  "lang": "eng",
  "title": "Hello!",
  "Message": "This is English",
  "goefttapping": "GO EFT Tapping",
  "thesound": "The sound can be interrupted by pressing any button.",
  "copyright": "©",
  "eftintro": "EFT Intro...",
  "youreft": "YOUR EFT",
  "contactme": "CONTACT ME",
  "sharingiscaring": "Sharing is caring!",
  "disclaimer": "Through continued use of this app, you take responsibility for your own health. Your recordings are erased at the end of each EFT session.",
  "myfeeling": "My feeling or \nsymptom is...",
  "theintensity": "The intensity \nis (0->10)...",
  "myfeelingrecorded": "My feeling or \nsymptom is recorded",
  "theintensityrecorded": "The intensity is recorded",
  "recordproblem": "Record problem",
  "recordintensity": "Record intensity",
  "chooselanguage": "Choose language below",
  "recordingproblem": "Recording problem...",
  "recordingintensity": "Recording intensity...",
  "recordprefferedemotion": "Record preferred \nemotion",
  "recording": "Recording...",
  "record": "Record",
  "whenihavethis": "When I have this: \n[feeling or symptom]",
  "ichoosetofeel": "I choose to feel: \n[preferred emotion]",
  "ihaveaquestion": "[From GO EFT Tapping app] I have a question",
  "hellosara": "Hello Sara!",
  "acupoints2": "2. Top of head\n3. Eyebrow\n4. Side of eye\n5. Under eye\n6. Under nose\n7. Chin\n8. Collarbone\n9. Under arm\n10. Inside Wrist",
  "acupoints": "1. Side of hand\n (Karate chop point)",
  "pagebtitle": "Record your problem",
  "pageetitle": "We tap together",
  "pageftitle": "Bridge to Better!",
  "checkout": "check out GO EFT TAPPING app!",
  "takealook": "Take a look at this app!"
};
static const Map<String,dynamic> sv = {
  "lang": "swe",
  "title": "Hello Sw!",
  "Message": "This is Swedish",
  "goefttapping": "GO EFT Tapping",
  "thesound": "Ljudet kan avbrytas med vilken knapp som helst.",
  "copyright": "©",
  "eftintro": "EFT INTRO",
  "youreft": "DIN EFT ",
  "contactme": "Kontakta mig",
  "sharingiscaring": "Att dela är omtänksamt!",
  "disclaimer": "Genom fortsatt användning av denna app,så tar du eget ansvar för din hälsa. Dina inspelningar raderas vid slutet av varje EFT session.",
  "myfeeling": "Min känsla eller \nsymptom är...",
  "theintensity": "Intensiteten \när (0->10) ...",
  "myfeelingrecorded": "Känslan eller \n symptomet är inspelat",
  "theintensityrecorded": "Intensiteten är inspelad",
  "recordproblem": "Inspelning \nav problemet",
  "recordintensity": "Inspelning \nav intensiteten",
  "chooselanguage": "Välj språk nedan",
  "recordingproblem": "Inspelning pågår...",
  "recordingintensity": "Inspelning pågår...",
  "recordprefferedemotion": "Inspelning av\nföredragen känsla",
  "recording": "Inspelning pågår...",
  "record": "Spela in",
  "whenihavethis": "När jag känner av denna... \n(känsla eller symptom) ",
  "ichoosetofeel": "så väljer jag \n(bättre känsla)",
  "ihaveaquestion": "[Från GO EFT Tapping appen] Jag har en fråga/fundering",
  "hellosara": "Hejsan Sara!",
  "acupoints2": "2. Huvudet\n3. Ögonbrynet\n4. Sidan av ögat\n5. Under ögat\n6. Under näsan\n7. Hakan, under läppen\n8. Nyckelbenspunkten,\n  eller handflatan \n  på nyckelbenen\n9. Under armen\n10. Handloven",
  "acupoints": "1. Sidan av handen\n(karatepunkten)",
  "pagebtitle": "Spela in ditt problem",
  "pageetitle": "Vi knackar tillsammans",
  "pageftitle": "Bro till Bättring",
  "checkout": "Titta på denna GO EFT Tapping app!",
  "takealook": "Ta en titt på den här appen!"
};
static const Map<String,dynamic> uk = {
  "lang": "swe",
  "title": "Hello Sw!",
  "Message": "This is Swedish",
  "goefttapping": "GO EFT Tapping",
  "thesound": "Ljudet kan avbrytas med vilken knapp som helst",
  "yourrecording": "Dina inspelningar raderas vid slutet av varje EFT session",
  "copyright": "©",
  "eftintro": "EFT INTRO",
  "youreft": "DIN EFT ",
  "contactme": "Kontakta mig",
  "sharingiscaring": "Att dela är omtänksamt!",
  "disclaimer": "Jag har hört/läst introduktionen \noch tar eget ansvar för mitt\nknackande.",
  "myfeeling": "Min känsla eller \nsymptom är...",
  "theintensity": "Intensiteten \när (0->10) ...",
  "myfeelingrecorded": "Känslan eller \n symptomet är inspelat",
  "theintensityrecorded": "Intensiteten är inspelad",
  "recordproblem": "Inspelning \nav problemet",
  "recordintensity": "Inspelning \nav intensiteten",
  "chooselanguage": "виберіть мову нижче",
  "recordingproblem": "Inspelning pågår...",
  "recordingintensity": "Inspelning pågår...",
  "recordprefferedemotion": "Inspelning av\nföredragen känsla",
  "recording": "Inspelning pågår...",
  "record": "Spela in",
  "whenihavethis": "När jag känner av denna... \n(känsla eller symptom) ",
  "ichoosetofeel": "så väljer jag \n(bättre känsla)",
  "ihaveaquestion": "[Från GO EFT Tapping appen] Jag har en fråga/fundering",
  "hellosara": "Hejsan Sara!",
  "acupoints2": "2. Huvudet\n3. Ögonbrynet\n4. Sidan av ögat\n5. Under ögat\n6. Under näsan\n7. Hakan, under läppen\n8. Nyckelbenspunkten,\n  eller handflatan \n  på nyckelbenen\n9. Under armen\n10. Handloven",
  "acupoints": "1. Sidan av handen\n(karatepunkten)",
  "pagebtitle": "Spela in ditt problem",
  "pageetitle": "Vi knackar tillsammans",
  "pageftitle": "GO EFT Bridge",
  "checkout": "Titta på denna GO EFT Tapping app!",
  "takealook": "Ta en titt på den här appen!"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en, "sv": sv, "uk": uk};
}
